[package]
name = "simd_slice_search"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memchr = "2.*"
multiversion = { version = "0.7", default-features = false }
seq-macro = "0.*"
